package com.app.questr.dto.challenge;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

/**
 * Request body for POST /api/v1/challenges/join.
 *
 * <p>The {@code inviteCode} must match the 6-char alphanumeric format
 * generated by {@code ChallengeService.generateUniqueInviteCode()}.
 */
public record JoinChallengeRequest(

        @NotBlank(message = "Invite code must not be blank")
        @Size(min = 6, max = 20, message = "Invite code must be 6–20 characters")
        @Pattern(regexp = "[A-Z0-9]+", message = "Invite code must contain only uppercase letters and digits")
        String inviteCode
) {}

